# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

resources:
  - ns.yml
  - crd.yml
  - sa.yml
  - rbac.yml
  - secret.yml
  - svc.yml
  - deploy.yml
  - pdb.yml
  - mwh.yml
  - vwh.yml

images:
  - name: openpolicyagent/gatekeeper
    newName: registry.sighup.io/fury/openpolicyagent/gatekeeper
    newTag: v3.14.0
