apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

resources:
  - crd.yml
  - ns.yml
  - rbac.yml
  - sa.yml
  - secret.yml
  - deploy.yml
  - svc.yml
  - vwh.yml

images:
  - name: openpolicyagent/gatekeeper
    newTag: v3.1.0
