# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - must_have_security_controls.yml
  - must_have_unique_ingresses.yml
  - must_have_liveness_probe.yml
  - must_have_readiness_probe.yml

patchesJson6902:
  - target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: SecurityControls
      name: enforce-deployment-and-pod-security-controls
    path: patches/all-matches.yml
  - target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: K8sUniqueIngressHost
      name: unique-ingress-host
    path: patches/ingress-matches.yml
  - target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: K8sLivenessProbe
      name: liveness-probe
    path: patches/all-matches.yml
  - target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: K8sReadinessProbe
      name: readiness-probe
    path: patches/all-matches.yml
